### ISSUE TITLE
could perform prediction based on run's results for breedR?

### ISSUE THREAD

**Issue by yzhlinscau** [famuvie/breedR#104]
Basically, it should be possible to perform prediction for linear models. It seems that prediction function did not exist in breedR package. Is it possible to predict one or more model item? If possible, how to write the codes? Thanks a lot.

**Comment by famuvie** [comment]
Hi,
for prediction of expected phenotype you can introduce individuals in the dataset with the response variable set to NA (see https://github.com/famuvie/breedR/wiki/Overview#prediction).

What do you mean by _predict one or more model item_?

Otherwise, please state these kind of questions in the [mailing list](http://groups.google.com/group/breedr), rather than here. Thanks.
