### ISSUE TITLE
breedr_ar not in namespace

### ISSUE THREAD

**Issue by timflutre** [famuvie/breedR#57]
I would like to use the `breedr_ar` function in the file `ar.R`. Can you make it available in the namespace?

**Comment by famuvie** [comment]
It has been designed to be internal (e.g. not much checking of user input).
Can you use it with `breedR:::breedr_ar()` or it fails?
Ultimately, I can make it available but hidden in the reference manuals and function index, if you really need it.

**Comment by timflutre** [comment]
I tried but it returned `NULL`. Here is a minimal example based on your [test](https://github.com/famuvie/breedR/blob/f78f84305d9532d8bbc7fa1b2e5d0eb8c9999c24/tests/testthat/test-AR.R#L11):
```
test.pos <- list(x = c(-2:3), y = 5:8/2)
test.coord <- as.matrix(expand.grid(test.pos$x[-2], test.pos$y))[-8, ]
test.rho <- c(.6, .8)
breedR:::breedr_ar(test.coord, test.rho, TRUE)

Call:
NULL

Error in if (x$order) { : l'argument est de longueur nulle
```

**Comment by famuvie** [comment]
Try assigning the result to some object:
```R
my_AR <- breedR:::breedr_ar(test.coord, test.rho, TRUE)
str(my_AR)
```

It works fine. The error happened because you tried (implicitly) to `print.ar` the result, which is a method defined in package `stats` for time series objects.
You see, this is another reason for why the method should remain internal. It avoids clashes with classes defined in other packages.
