### ISSUE TITLE
Is it convinient to add one new funciton to calculate standard error for heritability or correlation?

### ISSUE THREAD

**Issue by yzhlinscau** [famuvie/breedR#98]
I build one simple pakcage breedRPlus (https://github.com/yzhlinscau/breedRPlus), based on breedR. It is not convinient  to get standard error for  heritability or correlation with breedR at present. Therefore, I write some functions to get similar results to asreml-R.  asreml-R indeed has better results' presentation. Hope breedR can be better in the future.

**Comment by famuvie** [comment]
Dear Yuanzhen,

I'm very glad you could build upon breedR in order to make it suit your needs. I'm open to review pull-requests and to include your name among the contributors, if you wish.

That said, breedR's functionality to compute heritabilities, correlations and standard errors is described here: https://github.com/famuvie/breedR/wiki/Heritability
It includes a description of the delta method that you used in your package. But in my opinion, there are better options. In particular, as long as method is `AI` you can pass any formula to breedR and it does the computations for you, using Monte Carlo simulation. This is much safer as it does not rely on normal asymptotic distributions which are usually very bad approximations to small variances.

**Comment by yzhlinscau** [comment]
Dear famuvie,
Thanks for your response so quickly! It is my honor to have chance to do something for breedR.
