### ISSUE TITLE
could get anova() for fixed factors?

### ISSUE THREAD

**Issue by yzhlinscau** [famuvie/breedR#99]
I did not find any details to account for the significance for fixed factors when using breedR for linear mixed models. Is it possible to obtain something similar to aov table for fixed factors?

**Comment by famuvie** [comment]
Dear Yuanzhen,
I have considered the issue several times, as it is a recurrent request. However, it is not clear how to implement such a method in the context of Mixed Models, particularly with random effects at individual levels. The approach used by SAS (for instance) is questionable (see https://stat.ethz.ch/pipermail/r-help/2006-May/094765.html), which is why the authors of `lme4` neither supply p-values.
